### ISSUE TITLE
Build fails if there is an AS policy manually created

### ISSUE THREAD

**Issue by diogomelodantas** [veezor/maestro#8]
If there is an AS policy manually created build fails with the following error:

 "An error occurred (ValidationException) when calling the PutScalingPolicy operation: Only one TargetTrackingScaling policy for a given metric specification is allowed."

Is it the expected behavior?

**Comment by fagiani** [comment]
@diogomelodantas yes. Only one rule for each metric can exist. As we use a specific naming pattern, if a manual AS was created with another name it will conflict. The solution is to remove the manual AS and re-run maestro.
